# Generated by Django 5.1.4 on 2024-12-25 18:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='tfidf_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1024),
        ),
        migrations.AddField(
            model_name='article',
            name='time_spent_on',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_embedding_profile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1024)),
                ('tfidf_profile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1024)),
                ('watched_articles', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveArticles',
        ),
        migrations.CreateModel(
            name='ActiveArticles',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.article',),
        ),
    ]
